version: '3.7'
services: 
    db:
      image: mongo
    docker-fastapi:
        container_name: docker-fastapi
        build: 
            context: ./backend/
            dockerfile: Dockerfile
        restart: always
    nginx:
        depends_on: 
            - docker-fastapi
        container_name: proxy-app
        build: 
            context: ./frontend/
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always